name: Build&Deploy

on:
  workflow_dispatch:
    inputs:
      deploy_branch:
        description: 'Select branch to deploy'
        required: true
        default: 'main'
      target_env:
        description: 'Target environment (qa, staging, prod)'
        required: true
        default: 'qa'
        type: choice
        options:
          - qa
          - staging
          - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_branch }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_branch }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm test

  deploy:
    needs: test
    runs-on: ubuntu-latest
    environment:
      name: ${{ github.event.inputs.target_env }}
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ vars.AWS_REGION }}
      S3_BUCKET: ${{ vars.S3_BUCKET }}
      APPLICATION_NAME: ${{ vars.APPLICATION_NAME }}
      ENVIRONMENT_NAME: ${{ secrets.ENVIRONMENT_NAME }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.deploy_branch }}
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: zip -r deploy.zip . -x "node_modules/*"
      - name: Upload to S3
        run: aws s3 cp deploy.zip s3://$S3_BUCKET/deploy-${{ github.run_id }}.zip --region $AWS_REGION
      - name: Deploy to Elastic Beanstalk
        run: |
          aws elasticbeanstalk create-application-version \
            --application-name "$APPLICATION_NAME" \
            --version-label "ver-${{ github.run_id }}" \
            --source-bundle S3Bucket="$S3_BUCKET",S3Key="deploy-${{ github.run_id }}.zip" \
            --region $AWS_REGION

          aws elasticbeanstalk update-environment \
            --environment-name "$ENVIRONMENT_NAME" \
            --version-label "ver-${{ github.run_id }}" \
            --region $AWS_REGION
